### ISSUE TITLE
Option to disable info logs

### ISSUE THREAD

**Issue by pietrofxq** [Duroktar/vscode-npm-scripts#2]
Hi, I love this plugin for vs code, but the info messages at the top really annoy me because I have to keep closing them all the time. Is there a way to disable these info messages?

**Comment by Duroktar** [comment]
Hey, thanks! Currently there is no way to disable it, but I can add it in ASAP.

**Comment by Duroktar** [comment]
All done! So you'll probably want to set this in under "User settings" so it's global .. 
```
  ...
  "npm-scripts.showStartNotification": false
```

**Comment by pietrofxq** [comment]
Thank you
