### ISSUE TITLE
Workspace support [discussion]

### ISSUE THREAD

**Issue by Duroktar** [Duroktar/vscode-npm-scripts#4]
# Workspaces

I'd like to add support for workspaces but I'm not totally sure how I'd like to approach the UX. Here are some of my ideas..

## In a directory with a single workspace
1 - No changes to Tree View

```
    start
    test
    deploy
    ...
```

2 - Add a single top level containing the scripts in the Tree View

```
  top-level-package-name
    - start
    - test
    - deploy
    - ...
```

## In a directory with multiple workspaces

1 - Add a top level workspace for each set of scripts in the Tree View
```
  workspace1
    - start
    - test
    - deploy
    - ...
  workspace2
    - start
    - test
    - deploy
    - ...
  workspace...
    - ...
```

2 - Prefix the scripts with the workspace name
```
    - workspace1/start
    - workspace1/test
    - workspace1/deploy
    - workspace1/...
    - workspace2/start
    - workspace2/test
    - workspace2/deploy
    - workspace2/...
```

Right now I'm leaning on solutions 1 and 1 respectively from above. Leave your votes below or I'll have to pick for you :smiley: 

Note: I know I said I would implement this much sooner, but the package got many more downloads than I expected and I didn't want to ruin the experience for anyone. I also was busy on other projects (still am) and will be starting a new job soon so I've also been preparing for that. In other words, a PR with a working solution to the workspace problem would likely be accepted with very little resistance. If you get what I'm putting down there :wink:.

Thanks :beers:

**Comment by futagoza** [comment]
I'm also for `1` and `1` 👍

**Comment by Duroktar** [comment]
I'm planning on implementing this on the weekend FWIW. Looks like 1 and 1 will be the way to go unless a bunch of votes come in otherwise; we'll see. Thanks for everyone voting so far, keep em coming.

**Comment by adrianjost** [comment]
I'm also for 1 and 1 and hope to see this feature soon :)

**Comment by Duroktar** [comment]
@futagoza @adrianjost This has been implemented (finally) :tada: 

I'll close this up but let me know if there's any issues.

Enjoy  :smiley:
